# Generated by Django 4.2 on 2023-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('book_title', models.CharField(blank=True, max_length=128)),
                ('publisher', models.CharField(blank=True, max_length=64)),
                ('year', models.IntegerField(blank=True, max_length=4)),
                ('content', models.CharField(max_length=8500)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
