# Generated by Django 4.2 on 2023-05-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
